### ISSUE TITLE
Relay client: Identical transaction fails through the client but succeeds through the Defender Relay dashboard

### ISSUE THREAD

**Issue by ndavd** [OpenZeppelin/defender-client#133]
The transaction kept reverting without a reason through the client (https://testnet.bscscan.com/tx/0xd117163bd32a4a40ca7ed8bc00c3f945d7dd7dfb119233650ffe0160ac8bd14a).
So I thought about trying the same exact transaction without using the client and it worked https://testnet.bscscan.com/tx/0xc021efa412ea5e7c5542eb566ed824e266ee6cc9b303f6559b22c9447ce816b5

**Comment by ernestognw** [comment]
Hey @ndavd, thanks for reaching out.
I can see that the tx data is exactly the same, but I can't think of a way in which the relayer is causing it when using the client, since the transaction data is the same.

Do you know if there's any potential state change that might cause the issue? I'll still take a look at your contracts, but any detail regarding how the client might cause a different behavior is appreciated

**Comment by ernestognw** [comment]
I'm closing, but feel free to open if there's any suggestion to improve the client.

Best!
